// Package generator converts AST to GitHub Actions YAML
package generator

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"

	"golang-vibe-coding/internal/ast"
)

// GitHubActionsWorkflow represents the complete GitHub Actions workflow structure
type GitHubActionsWorkflow struct {
	Name string                       `yaml:"name"`
	On   interface{}                  `yaml:"on"`
	Jobs map[string]*GitHubActionsJob `yaml:"jobs"`
	Env  map[string]string            `yaml:"env,omitempty"`
}

// GitHubActionsJob represents a job in GitHub Actions format
type GitHubActionsJob struct {
	Name           string                 `yaml:"name,omitempty"`
	RunsOn         string                 `yaml:"runs-on"`
	Steps          []*GitHubActionsStep   `yaml:"steps"`
	Needs          interface{}            `yaml:"needs,omitempty"`
	If             string                 `yaml:"if,omitempty"`
	Env            map[string]string      `yaml:"env,omitempty"`
	Strategy       *GitHubActionsStrategy `yaml:"strategy,omitempty"`
	TimeoutMinutes int                    `yaml:"timeout-minutes,omitempty"`
	ContinueOnErr  bool                   `yaml:"continue-on-error,omitempty"`
}

// GitHubActionsStep represents a step in GitHub Actions format
type GitHubActionsStep struct {
	Name string            `yaml:"name,omitempty"`
	ID   string            `yaml:"id,omitempty"`
	Uses string            `yaml:"uses,omitempty"`
	Run  string            `yaml:"run,omitempty"`
	With map[string]string `yaml:"with,omitempty"`
	Env  map[string]string `yaml:"env,omitempty"`
	If   string            `yaml:"if,omitempty"`
}

// GitHubActionsStrategy represents job strategy in GitHub Actions format
type GitHubActionsStrategy struct {
	Matrix      map[string][]string `yaml:"matrix,omitempty"`
	FailFast    *bool               `yaml:"fail-fast,omitempty"`
	MaxParallel int                 `yaml:"max-parallel,omitempty"`
}

// Generator handles conversion from AST to GitHub Actions YAML
type Generator struct {
	workflow *ast.Workflow
}

// New creates a new generator instance
func New(workflow *ast.Workflow) *Generator {
	return &Generator{
		workflow: workflow,
	}
}

// GenerateYAML converts the AST to GitHub Actions YAML
func (g *Generator) GenerateYAML() (string, error) {
	if g.workflow == nil {
		return "", fmt.Errorf("no workflow provided")
	}

	yamlWorkflow := g.convertWorkflow()

	yamlBytes, err := yaml.Marshal(yamlWorkflow)
	if err != nil {
		return "", fmt.Errorf("failed to marshal YAML: %w", err)
	}

	// Add header comment
	yamlString := "# Generated by GitHub Actions DSL\n" + string(yamlBytes)
	return yamlString, nil
}

// convertWorkflow converts AST workflow to GitHub Actions format
func (g *Generator) convertWorkflow() *GitHubActionsWorkflow {
	yamlWorkflow := &GitHubActionsWorkflow{
		Name: g.workflow.Name,
		Jobs: make(map[string]*GitHubActionsJob),
		Env:  g.workflow.Env,
	}

	// Convert triggers
	yamlWorkflow.On = g.convertTriggers(g.workflow.On)

	// Convert jobs
	for jobName, job := range g.workflow.Jobs {
		yamlWorkflow.Jobs[jobName] = g.convertJob(job)
	}

	return yamlWorkflow
}

// convertTriggers converts AST triggers to GitHub Actions format
func (g *Generator) convertTriggers(triggers []ast.Trigger) interface{} {
	if len(triggers) == 0 {
		return "push" // default trigger
	}

	if len(triggers) == 1 {
		trigger := triggers[0]
		if len(trigger.Filters) == 0 {
			return trigger.Event
		}

		// Return structured trigger with filters
		return map[string]interface{}{
			trigger.Event: trigger.Filters,
		}
	}

	// Multiple triggers
	triggerMap := make(map[string]interface{})
	for _, trigger := range triggers {
		if len(trigger.Filters) == 0 {
			triggerMap[trigger.Event] = nil
		} else {
			triggerMap[trigger.Event] = trigger.Filters
		}
	}

	return triggerMap
}

// convertJob converts AST job to GitHub Actions format
func (g *Generator) convertJob(job *ast.Job) *GitHubActionsJob {
	yamlJob := &GitHubActionsJob{
		Name:           job.Name,
		RunsOn:         job.RunsOn,
		Steps:          []*GitHubActionsStep{},
		Env:            job.Env,
		If:             job.If,
		TimeoutMinutes: job.TimeoutMin,
		ContinueOnErr:  job.ContinueOnErr,
	}

	// Convert needs
	if len(job.Needs) > 0 {
		if len(job.Needs) == 1 {
			yamlJob.Needs = job.Needs[0]
		} else {
			yamlJob.Needs = job.Needs
		}
	}

	// Convert strategy
	if job.Strategy != nil {
		yamlJob.Strategy = &GitHubActionsStrategy{
			Matrix:      job.Strategy.Matrix,
			FailFast:    job.Strategy.FailFast,
			MaxParallel: job.Strategy.MaxParallel,
		}
	}

	// Convert steps
	for _, step := range job.Steps {
		yamlJob.Steps = append(yamlJob.Steps, g.convertStep(step))
	}

	return yamlJob
}

// convertStep converts AST step to GitHub Actions format
func (g *Generator) convertStep(step *ast.Step) *GitHubActionsStep {
	yamlStep := &GitHubActionsStep{
		Name: step.Name,
		ID:   step.ID,
		Uses: step.Uses,
		Run:  step.Run,
		With: step.With,
		Env:  step.Env,
		If:   step.If,
	}

	// Remove empty maps to keep YAML clean
	if len(yamlStep.With) == 0 {
		yamlStep.With = nil
	}
	if len(yamlStep.Env) == 0 {
		yamlStep.Env = nil
	}

	return yamlStep
}

// ValidateWorkflow performs basic validation on the workflow
func (g *Generator) ValidateWorkflow() []string {
	var errors []string

	if g.workflow == nil {
		return append(errors, "workflow is nil")
	}

	if strings.TrimSpace(g.workflow.Name) == "" {
		errors = append(errors, "workflow name cannot be empty")
	}

	if len(g.workflow.Jobs) == 0 {
		errors = append(errors, "workflow must have at least one job")
	}

	// Validate jobs
	for jobName, job := range g.workflow.Jobs {
		if strings.TrimSpace(job.RunsOn) == "" {
			errors = append(errors, fmt.Sprintf("job '%s' must specify runs-on", jobName))
		}

		if len(job.Steps) == 0 {
			errors = append(errors, fmt.Sprintf("job '%s' must have at least one step", jobName))
		}

		// Validate steps
		for i, step := range job.Steps {
			if strings.TrimSpace(step.Uses) == "" && strings.TrimSpace(step.Run) == "" {
				errors = append(errors, fmt.Sprintf("job '%s' step %d must have either 'uses' or 'run'", jobName, i+1))
			}

			if strings.TrimSpace(step.Uses) != "" && strings.TrimSpace(step.Run) != "" {
				errors = append(errors, fmt.Sprintf("job '%s' step %d cannot have both 'uses' and 'run'", jobName, i+1))
			}
		}
	}

	return errors
}

// GenerateExample generates an example DSL file for documentation
func GenerateExample() string {
	return `// GitHub Actions DSL Example
// This file demonstrates the syntax for defining GitHub Actions workflows

workflow "CI Pipeline" {
    on = "push"
    
    job "build" {
        runs-on = "ubuntu-latest"
        
        step "Checkout" uses = "actions/checkout@v3"
        
        step "Setup Go" {
            uses = "actions/setup-go@v3"
            with {
                go-version = "1.19"
            }
        }
        
        step "Build" run = "go build ./..."
        
        step "Test" {
            run = "go test ./..."
            env {
                CGO_ENABLED = "0"
                GOOS = "linux"
            }
        }
    }
    
    job "deploy" {
        runs-on = "ubuntu-latest"
        needs = "build"
        if = "github.ref == 'refs/heads/main'"
        
        step "Deploy" run = "echo 'Deploying application...'"
    }
}

// Matrix build example (for future enhancement):
// job "test-matrix" {
//     runs-on = "ubuntu-latest"
//     strategy {
//         matrix {
//             go-version = ["1.18", "1.19", "1.20"]
//             os = ["ubuntu-latest", "windows-latest", "macos-latest"]
//         }
//     }
//     step "Test" run = "go test ./..."
// }

// Environment variables example:
// workflow "Production Deploy" {
//     env {
//         NODE_ENV = "production"
//         API_URL = "https://api.example.com"
//     }
//     // ... jobs
// }

// Advanced triggers example (for future enhancement):
// workflow "PR Checks" {
//     on {
//         pull_request {
//             branches = ["main", "develop"]
//             paths = ["src/**", "**.go"]
//         }
//         push {
//             branches = ["main"]
//         }
//     }
//     // ... jobs
// }
`
}

// FormatYAML formats and validates YAML output
func FormatYAML(yamlContent string) (string, error) {
	var parsed interface{}
	err := yaml.Unmarshal([]byte(yamlContent), &parsed)
	if err != nil {
		return "", fmt.Errorf("invalid YAML: %w", err)
	}

	formatted, err := yaml.Marshal(parsed)
	if err != nil {
		return "", fmt.Errorf("failed to reformat YAML: %w", err)
	}

	return string(formatted), nil
}
